server:
  port: 9005

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost/[MasterService]AccountDB
    username: postgres
    password: 2392
  jpa:
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka


